<a href="https://colab.research.google.com/github/deokarniharika/data-science-exercises.py/blob/main/NumPy/python_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
print("Python-Data-Science-Exercises")

Python-Data-Science-Exercises


In [2]:
import numpy as np
print(np.__version__)

1.21.6


In [29]:
# gives the numbers from 0-99 (arange function)
print(np.arange(10,100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [28]:
print(np.ones(shape=(10,10), dtype="float")*255)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


In [27]:
C=[]
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

for i in range(0,4):
    if(A[i]>B[i]):
        C.append(True)
    else:
        C.append(False)
        
print(C)
print(A>B)
print(np.greater(A,B))

[True, False, False, False]
[ True False False False]
[ True False False False]


In [26]:
print(np.zeros(shape=(4,4), dtype="int"))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [25]:
print(np.arange(10,100).reshape(9,10))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [24]:
print(np.eye(N=6, dtype="int"))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [23]:
np.random.seed(10)
print(np.random.rand(30))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


In [21]:
np.random.seed(20)
print(np.random.rand(10, 4))

[[0.5881308  0.89771373 0.89153073 0.81583748]
 [0.03588959 0.69175758 0.37868094 0.51851095]
 [0.65795147 0.19385022 0.2723164  0.71860593]
 [0.78300361 0.85032764 0.77524489 0.03666431]
 [0.11669374 0.7512807  0.23921822 0.25480601]
 [0.85762553 0.94977903 0.56168686 0.17878052]
 [0.77025193 0.49238104 0.63125307 0.83949792]
 [0.4610394  0.49794007 0.67941112 0.65078591]
 [0.26879524 0.06732467 0.77144514 0.48098413]
 [0.32920641 0.51064106 0.26362883 0.31051155]]


In [31]:
#this function gives numbers from the variable 'start' to the variable 'stop'
print(np.linspace(start=0, stop=1, num=11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [14]:
#The seed() method is used to initialize the random number generator.
#The random number generator needs a number to start with (a seed value), to be able to generate a random number.

np.random.seed(42)
print(np.random.choice(range(1,50), size=6, replace=False))

[14 46 48 45 18 28]


In [20]:
#this method helps in making a diagonal matrix
np.diag(np.arange(8))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7]])